version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:current  # Use a CircleCI Node.js image

    steps:
      - checkout  # Step to check out your code from GitHub

      - run:
          name: Change Directory to main
          command: cd main
          # Change to the 'main' directory where package.json is located

      - run:
          name: List Files in main Directory
          command: |
            cd main
            ls -la  # Lists all files in the 'main' directory to confirm the presence of package.json

      - run:
          name: Checking for package.json
          command: |
            cd main
            if [ -f package.json ]; then
              echo "package.json found"
            else
              echo "package.json not found, exiting"
              exit 1
            fi

      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "main/yarn.lock" }}
            # Adjusted cache key to check for yarn.lock in the 'main' directory

      - run:
          name: Install Dependencies
          command: |
            cd main
            if [ -f yarn.lock ]; then
              yarn install
            else
              npm install
            fi
          # Installs dependencies using yarn if yarn.lock is present in the 'main' directory, otherwise npm

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-cache-{{ checksum "main/yarn.lock" }}
          # Saves Yarn cache for future builds

      - run:
          name: Run Tests
          command: |
            cd main
            if [ -f yarn.lock ]; then
              yarn test
            else
              npm test
            fi
          # Runs tests based on the available package manager in the 'main' directory

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
