version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:current

    steps:
      - checkout

      - run:
          name: List All Files Recursively
          command: ls -laR
          # Recursively lists all files and directories to understand the project structure

      - run:
          name: Check for package.json
          command: |
            if [ -f package.json ]; then
              echo "package.json found in root"
            elif [ -f main/package.json ]; then
              echo "package.json found in main directory"
            else
              echo "package.json not found, exiting"
              exit 1
            fi

      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "main/yarn.lock" }}

      - run:
          name: Install Dependencies
          command: |
            if [ -f main/package.json ]; then
              cd main && yarn install
            elif [ -f package.json ]; then
              yarn install
            else
              echo "No package.json found, skipping dependency installation"
              exit 1
            fi

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-cache-{{ checksum "main/yarn.lock" }}

      - run:
          name: Run Tests
          command: |
            if [ -f main/package.json ]; then
              cd main && yarn test
            elif [ -f package.json ]; then
              yarn test
            else
              echo "No package.json found, cannot run tests"
              exit 1
            fi

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
