version: 2.1

jobs:
  basic-build:
    docker:
      - image: cimg/base:stable  # Basic image with minimal dependencies

    steps:
      # Step 1: Checkout the code from the repository
      - checkout

      # Step 2: List all files to confirm checkout
      - run:
          name: List All Files in Root
          command: ls -laR
          # Recursively list all files to verify the structure after checkout

      # Step 3: Display Environment Variables
      - run:
          name: Display Environment Variables
          command: env
          # Lists all environment variables for debugging purposes

      # Step 4: Create a Sample File
      - run:
          name: Create Sample File
          command: |
            echo "This is a sample file created during the build" > sample.txt
            echo "File created at $(date)" >> sample.txt
            cat sample.txt
          # Creates a sample file and displays its contents

      # Step 5: Archive the File as an Artifact
      - persist_to_workspace:
          root: .
          paths:
            - sample.txt
          # Stores the `sample.txt` file as an artifact for later access

      # Step 6: Print Disk Space and Memory Usage
      - run:
          name: Check System Resources
          command: |
            df -h
            free -m
          # Prints disk space and memory usage for debugging system resources

      # Step 7: Display CircleCI Job Information
      - run:
          name: Display Job Info
          command: |
            echo "Job ID: ${CIRCLE_WORKFLOW_ID}"
            echo "Job Number: ${CIRCLE_BUILD_NUM}"
            echo "Branch: ${CIRCLE_BRANCH}"
          # Prints CircleCI-specific environment variables for job tracking

workflows:
  basic-workflow:
    jobs:
      - basic-build
