version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:current

    steps:
      - checkout

      - run:
          name: List Files at Root Level
          command: ls -la
          # Lists files in the root to check if 'main' is present

      - run:
          name: Checking for main Directory
          command: |
            if [ -d main ]; then
              echo "main directory found"
            else
              echo "main directory not found, exiting"
              exit 1
            fi

      - run:
          name: Checking for package.json in main
          command: |
            if [ -f main/package.json ]; then
              echo "package.json found in main"
            else
              echo "package.json not found in main, exiting"
              exit 1
            fi

      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "main/yarn.lock" }}

      - run:
          name: Install Dependencies
          command: |
            cd main && \
            if [ -f yarn.lock ]; then
              yarn install
            else
              npm install
            fi
          # Installs dependencies using yarn if yarn.lock is present in the 'main' directory, otherwise npm

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-cache-{{ checksum "main/yarn.lock" }}

      - run:
          name: Run Tests
          command: |
            cd main && \
            if [ -f yarn.lock ]; then
              yarn test
            else
              npm test
            fi
          # Runs tests based on the available package manager in the 'main' directory

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
