version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:current

    steps:
      - checkout  # Ensure te code is checked out from the repository

      - run:
          name: Spin up environment
          command: echo "Environment setup complete"

      - run:
          name: Prepare Environment Variables
          command: |
            export NODE_ENV=development
            echo "NODE_ENV set to development"

      - run:
          name: Remove temporary links
          command: |
            echo "Removing temporary links (if any)"


workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
