version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0  # Use an OpenJDK 17 image with Maven pre-installed

    steps:
      # Step 1: Checkout the code from the repository
      - checkout

      # Step 2: Cache Maven dependencies to speed up builds
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-

      # Step 3: Run Maven to resolve dependencies
      - run:
          name: Install Dependencies
          command: mvn dependency:resolve

      # Step 4: Save dependencies to cache
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}

      # Step 5: Compile the project
      - run:
          name: Compile Project
          command: mvn compile

      # Step 6: Run Tests
      - run:
          name: Run Calculator Tests
          command: mvn test
          # This will run all tests in the project, including CalculatorTest.java

      # Step 7: Archive Test Results
      - store_test_results:
          path: target/surefire-reports
          # Stores test results for CircleCI insights

      - store_artifacts:
          path: target
          # Stores all build artifacts, including compiled classes and test reports

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
